### ISSUE TITLE
Issue get paginate data with relationship table.

### ISSUE THREAD

**Issue by dwcahyo23** [nodeteamdev/nestjs-prisma-pagination#6]
How to paginate with relationship table ?

`this.paginate(this.prisma.user.findMany({ includes:  { roles: true} }))`

**Comment by dwcahyo23** [comment]
`async findAllLinkZMch(
		where: Prisma.Link_ZMchWhereInput,
		orderBy: Prisma.Link_ZMchOrderByWithRelationInput
	): Promise<PaginatorTypes.PaginatedResult<any>> {
		const include: Prisma.Link_ZMchInclude = {
			mstZ20: true,
			mstMch: true
		};
		return this.paginate(this.prisma.link_ZMch, {
			where,
			orderBy,
			include
		});
	}`

**Comment by dwcahyo23** [comment]
![Screenshot 2024-04-19 230854](https://github.com/nodeteamdev/nestjs-prisma-pagination/assets/101392599/9d8926c8-040b-439e-b411-673a97de69c3)

**Comment by Vladyslav317** [comment]
Hi @dwcahyo23 ! You can only use include if you have 2 models that are connected to each other.
mstZ20 and mstMch are these 2 models connected through link_ZMch?

If the issue persists, could you please provide me with a screenshot of your schema? This will help me understand your situation better.

**Comment by dwcahyo23** [comment]
@Vladyslav317 ok thanks this is closed

**Comment by dwcahyo23** [comment]
@Vladyslav317 ok thanks, but this is closed
